# Generated by Django 5.2.5 on 2025-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Въведи телефонен номер във формат +359...', max_length=14, verbose_name='Телефонен номер')),
                ('working_time', models.TextField()),
                ('address', models.TextField(max_length=200)),
                ('custom_message', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контактна информация',
                'verbose_name_plural': 'Контактни данни',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-instagram', 'Instagram'), ('fa-twitter', 'Twitter'), ('fa-youtube', 'YouTube'), ('fa-linkedin', 'LinkedIn'), ('fa-globe', 'Уебсайт'), ('fa-link', 'Общ линк'), ('custom', 'Ръчно въвеждане')], default='custom', help_text="Избери икона за социалната платформа или избери 'Ръчно' за персонализирана стойност", max_length=50)),
                ('custom_icon', models.CharField(blank=True, help_text="Ако е избрано 'Ръчно', въведи CSS клас за иконата (напр. 'fa-tiktok')", max_length=50)),
                ('appearance_order', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
