# Generated by Django 5.2.5 on 2025-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_email_sent_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
